{% set name = "snowline" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dd1eeb23300b68a9c9171851e4daef98b676d02f90f5d304c06d1ccc53f5471a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pytest-runner
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - pypmc
    - iminuit
    # the following two are for (optional) plot functionality
    - matplotlib-base
    - corner

test:
  imports:
    - snowline
  source_files:
    - tests/*
  requires:
    - pytest >=3
    - pip
    - openssh   # see https://github.com/open-mpi/ompi/issues/3625
    - python {{ python_min }}
  commands:
    - pip check
    - pytest -sxv tests/

about:
  home: https://johannesbuchner.github.io/snowline/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Fit and compare models very quickly. MCMC-free.

  description: |
    Fit and compare models very quickly. MCMC-free.

    Posterior distributions and corner plots without MCMC? No dealing with convergence criteria?

    Yes!

    Tailored for low-dimensional (d<10) problems with a single mode, this package automatically finds the best fit and uses the local covariance matrix as a Laplace Approximation. Then Importance Sampling and Variational Bayes come in to improve from a single-gaussian approximation to more complex shapes. This allows sampling efficiently in some problems, and provides a estimate for the marginal likelihood.

    This package is built on top the excellent (i)minuit and pypmc packages.
  doc_url: https://johannesbuchner.github.io/snowline/
  dev_url: https://github.com/JohannesBuchner/snowline

extra:
  recipe-maintainers:
    - JohannesBuchner
